### ISSUE TITLE
Not wroking properly

### ISSUE THREAD

**Issue by TheBlackBush** [asafs/reverse-subtitles#1]
Love your script, this is exactly what i need, but there are some issues that i hope that you can correct them.

- Can you make it that it will work on both ways? (reverse & unreverse)
- when i try to use your script as is it make a new row with the punctuation

Here some examples (attached)

[UnReverse Punctuation.zip](https://github.com/asafs/reverse-subtitles/files/1424201/UnReverse.Punctuation.zip)
[Reverse Punctuation.zip](https://github.com/asafs/reverse-subtitles/files/1424202/Reverse.Punctuation.zip)

**Comment by asafs** [comment]
Hi,
Sorry for the very long delay in the response.
I made a very small fix with the encoding, and was able to convert your file correctly (attached).
Not sure it fixed your issue, but please try again.

About the unreverse, i tested it and it should work as is. let me know if it doesn't work for you after the fix.

[Annabelle 2 Creation (2017).REV.srt.zip](https://github.com/asafs/reverse-subtitles/files/2016754/Annabelle.2.Creation.2017.REV.srt.zip)

**Comment by TheBlackBush** [comment]
Hi thanks for the fix but i'm getting sn error now:  
```
BuSHari@DiskStation:~/reverse-subtitles$ python rev.py "Annabelle.heb.forced.srt"
Found 1 files. Starting to convert
Converting File: Annabelle.heb.forced.srt
Traceback (most recent call last):
  File "rev.py", line 101, in <module>
    Main()
  File "rev.py", line 91, in Main
    ReversePuctuation(file, newFile)
  File "rev.py", line 40, in ReversePuctuation
    f = open(file, 'r', encoding="Windows-1255")
TypeError: 'encoding' is an invalid keyword argument for this function
```
